import './globals.css';
import { Inter } from 'next/font/google';
import { Provider } from '@/providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
    title: 'UCI Web Channel',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Provider>{children}</Provider>
            </body>
        </html>
    );
}
